add new extensions/plugins
canonical/postgresql-operator pull request #251
Opened 2023-10-16 11:16 UTC by TakoB222

2023-10-16 12:33 UTC, delgod commented on config.yaml
> +  plugin_uuid-ossp_enable:
```suggestion
  plugin_uuid_ossp_enable:
```

2023-10-16 17:40 UTC, delgod commented on config.yaml
> +  plugin_uuid-ossp_enable:
Unfortunately, the `-` symbol is prohibited for config options, please implement a workaround for extensions with `-` in the name.

2023-10-17 10:12 UTC, delgod approved these changes

2023-10-17 10:40 UTC, taurus-forever requested changes
Thank you! LGTM in general, but one typo.

@dragomirp please contact Artem in public MM and explain how to update library to pass CI tests. Thank you!

BTW: I have updated PR commit message to represent changes. TODO for Artem: 
1) add K8s PR
2) update documentation: 
* https://charmhub.io/postgresql/docs/r-supported-plugins-extensions
* https://charmhub.io/postgresql-k8s/docs/r-supported-plugins-extensions

2023-10-17 10:40 UTC, taurus-forever commented on tests/integration/test_plugins.py
> +            connection.cursor().execute(TABLEFUNC_EXTENSION_STATEMENT)
```suggestion
            connection.cursor().execute(TCN_EXTENSION_STATEMENT)
```

2023-10-20 17:54 UTC, marceloneppel approved these changes

2023-10-25 15:02 UTC, dragomirp commented on config.yaml
> +    description: Enable uuid_ossp extension
```suggestion
    description: Enable uuid-ossp extension
```

2023-10-25 15:05 UTC, dragomirp commented on src/charm.py
> +
Like in k8s, I think it's better to have a single override mapping.

2023-10-25 15:07 UTC, dragomirp commented on tests/integration/test_plugins.py
Like in k8s, I think it's better to have a single mapping and loop over it in config and test assertions.

2023-10-25 15:08 UTC, dragomirp commented
Hi, @TakoB222, added a few nitpicks. Please resync with main, there are conflicting changes but also a fix for the check lib failure.

2023-11-16 12:21 UTC, dragomirp commented
Hi, @TakoB222, please sync with main. This should handle any remaining CI breakages.

2023-11-16 13:39 UTC, dragomirp submitted a review, later dismissed

2023-11-16 13:45 UTC, marceloneppel submitted a review, later dismissed

2023-11-21 11:41 UTC, marceloneppel approved these changes

2023-11-21 13:27 UTC, taurus-forever approved these changes

2023-11-21 15:18 UTC, merged