[DPE-3202] Architecture specific snap revision
canonical/postgresql-operator pull request #345
Opened 2024-02-05 16:14 UTC by dragomirp

2024-02-05 21:42 UTC, taurus-forever requested changes
LGTM, but as discussed, please use `14/latest` snap track.

2024-02-05 23:02 UTC, dragomirp commented
> LGTM, but as discussed, please use `14/latest` snap track.

`14/latest` or `14/stable`? Currently it's set to `14/stable`.

2024-02-06 10:01 UTC, taurus-forever commented
> > LGTM, but as discussed, please use `14/latest` snap track.
> 
> `14/latest` or `14/stable`? Currently it's set to `14/stable`.

Midnight comment. sure `14/stable`. :-D

2024-02-06 10:04 UTC, taurus-forever approved these changes
tnx!

2024-02-06 11:54 UTC, marceloneppel approved these changes
LGTM!

2024-02-06 11:54 UTC, marceloneppel commented on src/charm.py
> +                        if type(revision) is dict:
I think it's not needed, but also not a problem to keep it here.

2024-02-06 12:09 UTC, dragomirp commented on src/charm.py
> +                        if type(revision) is dict:
Removed for simplicity's sake.

2024-02-06 12:22 UTC, marceloneppel approved these changes

2024-02-06 22:21 UTC, merged