[DPE-5713] Catch wrong parameters exception on bucket create function call
canonical/postgresql-operator pull request #701
Opened 2024-12-16 14:36 UTC by lucasgameiroborges

solves #661

2024-12-16 22:17 UTC, hloeung commented
Thank you for this!

2024-12-17 18:03 UTC, marceloneppel requested changes
I believe the fix is solving the issue commented on https://github.com/canonical/postgresql-operator/issues/661#issuecomment-2512875639, but not the original issue.

I see that the error is still happening by using the following steps:
```sh
sudo apt install net-tools

sudo openssl genrsa -out ~/ca.key 2048
sudo openssl req -x509 -new -nodes -key ~/ca.key -days 1024 -out ~/ca.crt -outform PEM -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
sudo openssl genrsa -out ~/server.key 2048
sudo openssl req -new -key ~/server.key -out ~/server.csr -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
export HOST_IP=$(lxc network list --format json | jq -r '.[]  | select(.name=="lxdbr0").config."ipv4.address"' | cut -d'/' -f1)
echo "subjectAltName = DNS:$HOST_IP,IP:$HOST_IP" > ~/extfile.cnf
sudo openssl x509 -req -in ~/server.csr -CA ~/ca.crt -CAkey ~/ca.key -CAcreateserial -out ~/server.crt -days 365 -extfile ~/extfile.cnf

sudo snap install microceph
sudo microceph cluster bootstrap
sudo microceph disk add loop,4G,3

sudo microceph enable rgw --ssl-certificate="$(sudo base64 -w0 ~/server.crt)" --ssl-private-key="$(sudo base64 -w0 ~/server.key)"

watch -c sudo snap logs microceph.rgw -n 20

sudo microceph.radosgw-admin user create --uid test --display-name test

charmcraft pack
juju deploy ./*.charm
juju deploy s3-integrator

juju config s3-integrator  endpoint="https://$HOST_IP" bucket="test" path="/test-$RANDOM" region="" s3-uri-style="path" # with missing tls-ca-chain config option.
juju relate s3-integrator postgresql

juju run s3-integrator/leader sync-s3-credentials access-key=XXX secret-key=XXX
```

2025-01-09 13:41 UTC, lucasgameiroborges commented
@marceloneppel Thanks for raising! It should be fixed now

2025-01-09 18:25 UTC, marceloneppel approved these changes
Thanks, @lucasgameiroborges! I tested the updated changes and LGTM!

Could you create a backlog ticket for the K8s charm? Thanks.

2025-01-14 00:00 UTC, dragomirp approved these changes

2025-01-19 23:39 UTC, merged