pgBackRest restore action
canonical/postgresql-operator pull request #83
Opened 2023-03-14 21:05 UTC by marceloneppel

2023-03-16 06:44 UTC, delgod requested changes

2023-03-16 06:44 UTC, delgod commented on src/backups.py
> +            for backup in backups
I think we need to add `show_failed: boot` flag to this function.
in one hand, we should return even failed backup id in `_on_create_backup_action`
in another hand we shouldn't try to restore failed backup in `_on_restore_action`
```suggestion
            for backup in backups
            if show_failed or not backup["error"]
```

2023-03-17 04:43 UTC, delgod approved these changes

2023-03-17 15:59 UTC, taurus-forever approved these changes
Tnx for taking care!

2023-03-17 17:37 UTC, dragomirp approved these changes

2023-03-17 17:39 UTC, merged

2023-03-17 17:39 UTC, marceloneppel commented on src/backups.py
> +            return
Good catch, Alex! I updated it on https://github.com/canonical/postgresql-operator/pull/83/commits/43a1e36f71d0b74ef01c57f2cd1865640bd802fa.